sonarr:
  url: 'http://localhost:8989'
  api_key: 'YOUR_SONARR_API_KEY'

trakt:
  client_id: "YOUR_TRAKT_API_CLIENT_ID"
  client_secret: "YOUR_TRAKT_API_CLIENT_SECRET"
  desired_episode_types: #these episode types will be used as the labels to be applied in Plex
    - "mid_season_finale"
    - "season_finale"
    - "series_finale"

plex:
  url: 'http://localhost:32400'
  token: 'YOUR_PLEX_TOKEN'
  library_title: 'TV Shows'

general:
  launch_method: 0 #0=menu, 1=Sonarr, 2=Trakt, 3=Both consecutively
  recent_days: 14
  skip_unmonitored: true
  skip_genres: true
  genres_to_skip:
    - "Talk Show"
    - "News"
    - "Stand-Up"
    - "Awards Show"
  skip_labels: true
  labels_to_skip:
    - "Skip"
    - "Exclude"
  label_series_in_plex: true
  plex_label: "Finale"
  remove_labels_if_no_longer_matched: true
  only_finale_unwatched: false

paths:
  path_mappings:
    # Examples:
    # windows_to_nas:
    #   "D:/Media/": "/volume1/Media/"
    # docker_to_nas:
    #   "/tv": "/volume1/Media/TV Shows"
    # Set your platform: 'windows', 'linux', 'nas', or 'docker'
  platform: "windows"